displayName: '${{env.CONTAINER_NAME}} load testing'
testPlan: '../../../src/KEDA.DAPR.Demo/src/tests/${__BeanShell( System.getenv("CONTAINER_NAME") )}/${{env.CONTAINER_NAME}}.jmx'
description: Load testing demo JMeter
engineInstances: 1
testId: apiiniciativa_loadtesting
testType: JMX
splitAllCSVs: False
failureCriteria: []
autoStop:
  errorPercentage: 90
  timeWindow: 60