name: ACA PROD PRODUCTS PYTHON API

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - src/Python.Store.ProductApi/**
jobs:
  Build-Publish-ACA:
    uses: ./.github/workflows/Template_ACA.yml
    with:      
      CONTAINER_NAME: product-python-api
      DOCKER_PATH: ./src/Python.Store.ProductApi/DockerFile
      DOCKER_BUILD_CONTEXT: ./src/Python.Store.ProductApi      
      ACA_ENVIRONMENT : prod
    secrets: inherit