name: ACA DEV PORTAL NET

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
    paths:
      - src/Store/**
      - src/Monitoring/**
jobs:
  Build-Publish-ACA:
    uses: ./.github/workflows/Template_ACA.yml
    with:
      CONTAINER_NAME: portal-net
      DOCKER_PATH: ./src/Store/Dockerfile
      DOCKER_BUILD_CONTEXT: ./src
      ACA_ENVIRONMENT : dev
    secrets: inherit