name: IAC DEPLOYMENT (DEV)
on:
  workflow_dispatch:
  push:
    branches: ["dev"]
    paths:
      - infra/**
jobs:
  Deploy_Baseline:
    uses: ./.github/workflows/Template_Bicep_IaC.yml
    with:
      LOCATION: ${{ vars.LOCATION }}
      TEMPLATE_FILE: "infra/csu_gh_adoption_main.bicep"
      PARAMETERS_FILE: "infra/csu_gh_adoption_dev.json"
      KIND: "create"
    secrets: inherit
