name: IAC PROD DEPLOYMENT
#env:
#  # Setting environment variables
#  NODE_ENV: production
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - infra/**
jobs:

  Deploy_Baseline:
    uses: ./.github/workflows/Tempate_Bicep_IaC.yml
    with:
        LOCATION: ${{ vars.LOCATION }}
        TEMPLATE_FILE: 'infra/csu_gh_adoption_main.bicep'
        PARAMETERS_FILE: 'infra/csu_gh_adoption_prod.json'
        KIND: 'create'
    secrets: inherit