name: IAC DEV DEPLOYMENT
on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]
    paths:
    - infra/**
jobs:

  Deploy_Baseline:
    uses: ./.github/workflows/Tempate_Bicep_IaC.yml
    with:
        LOCATION: 'centralus'
        TEMPLATE_FILE: 'infra/csu_gh_adoption_main.bicep'
        PARAMETERS_FILE: 'infra/csu_gh_adoption_dev.json'
        KIND: 'create' #'create'
    secrets: inherit