name: DAPR_KEDA_DEV
on:
  workflow_dispatch:
jobs:
  Enable_DAPR_KEDA:
    uses: ./.github/workflows/Template_DAPR_KEDA.yml
    with:
      KEDA_CONTAINER_NAMES: '["apipresupuesto", "apiarquitectura"]'
    secrets: inherit
