name: ACA JAVA VALIDATION

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
    - src/Java.Store.InventoryApi/**

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        language: ['java']

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        working-directory: ./src/Java.Store.InventoryApi
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
      working-directory: ./src/Java.Store.InventoryApi
    
 #  - name: Initialize CodeQL
 #    uses: github/codeql-action/init@v2      
 #    with:
 #      languages: ${{ matrix.language }}
 #      working-directory: ./src/Java.Store.InventoryApi

 #  - name: Autobuild
 #    uses: github/codeql-action/autobuild@v2
 #    with:
 #      working-directory: ./src/Java.Store.InventoryApi

 #  - name: Perform CodeQL Analysis
 #    uses: github/codeql-action/analyze@v2
 #    with:
 #      working-directory: ./src/Java.Store.InventoryApi