name: Template Load Testing

on:
  workflow_call:
    inputs:
      CONTAINER_NAME:
        required: true
        type: string
      ACA_ENVIRONMENT:
        required: true
        type: string
       
jobs:
  loadtesting:
    runs-on: ubuntu-latest
    #environment: ${{ inputs.ACA_ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Init Application env vars
        id: application_env_vars
        run: |
          APPLICATION_URL=$(az containerapp show --name ${{ inputs.CONTAINER_NAME }}  --resource-group ${{ vars.RESOURCE_GROUP }} --query 'properties.configuration.ingress.fqdn' --output tsv)
          echo "APPLICATION_URL=$APPLICATION_URL" >> $GITHUB_OUTPUT
          LOAD_TESTING_NAME=$(az resource list --resource-group ${{ vars.RESOURCE_GROUP }} --resource-type Microsoft.LoadTestService/loadTests --query "[].{Name:name}" --output tsv)
          echo "LOAD_TESTING_NAME=$LOAD_TESTING_NAME" >> $GITHUB_OUTPUT
          echo "Testing Application URL: $APPLICATION_URL"
      - name: 'Azure Load Testing'
        uses: azure/load-testing@v1
        with:
          #loadTestConfigFile: 'src/KEDA.DAPR.Demo/src/tests/${{ inputs.CONTAINER_NAME }}/config.yaml'
          loadTestConfigFile: './.github/workflows/loadtesting/config.yaml'
          loadTestResource: ${{ steps.application_env_vars.outputs.LOAD_TESTING_NAME }}
          resourceGroup: ${{ vars.RESOURCE_GROUP }}
          env: |
            [
              {
                "name": "CONTAINER_NAME",
                "value": "${{ inputs.CONTAINER_NAME }}"
              },
              {
                "name": "${{ inputs.CONTAINER_NAME }}_domain",
                "value": "${{ steps.application_env_vars.outputs.APPLICATION_URL }}"
              }
            ]
      - uses: actions/upload-artifact@v4.4.0
        with:
          name: loadTestResults
          path: ${{ github.workspace }}/loadTest