name: Template DAPR KEDA

on:
  workflow_call:
    inputs:
      CONTAINER_NAMES:
        required: true
        type: string

jobs:
  DAPR:
    runs-on: ubuntu-latest
    #needs: Deploy_Baseline
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Enable KEDA Scale Rule
        run: |
          DAPR_YAML_FILE='./src/KEDA.DAPR.Demo/src/components/pubsub-sandbox-servicebus.yaml'
          #Get container App Environtment name:
          ENVIRONMENT=$(az containerapp env list --resource-group ${{ vars.RESOURCE_GROUP }} --query '[0].name' --output tsv)
          #Get Service Bus Namespace Name:
          SERVICE_BUS_NAMESPACE_NAME=$(az servicebus namespace list --resource-group ${{ vars.RESOURCE_GROUP }} --query '[0].name' --output tsv)

          echo "Service Bus Namespace Name: $SERVICE_BUS_NAMESPACE_NAME" 
          echo "Container App Environment Name: $ENVIRONMENT"

          #Replace String "#{SERVICE_BUS_NAMESPACE}#" into DAPR_YAML_FILE
          sed -i "s/#{SERVICE_BUS_NAMESPACE}#/$SERVICE_BUS_NAMESPACE_NAME/g" $DAPR_YAML_FILE
          cat $DAPR_YAML_FILE


          az containerapp env dapr-component set \
          --name $ENVIRONMENT \
          --resource-group ${{ vars.RESOURCE_GROUP }} \
          --dapr-component-name pubsub-sandbox-servicebus \
          --yaml "${DAPR_YAML_FILE}"

  KEDA:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container_name: ${{ fromJson(inputs.CONTAINER_NAMES) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Enable KEDA Scale Rule (Secrets)
        run: |
          BACKEND_SERVICE_NAME="${{ matrix.container_name }}"

          SERVICE_BUS_NAMESPACE_NAME=$(az servicebus namespace list --resource-group ${{ vars.RESOURCE_GROUP }} --query '[0].name' --output tsv)
          echo "Service Bus Namespace Name: $SERVICE_BUS_NAMESPACE_NAME" 

          SERVICE_BUS_CONNECTION_STRING=$(az servicebus namespace authorization-rule keys list \
            --name RootManageSharedAccessKey \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --namespace-name $SERVICE_BUS_NAMESPACE_NAME \
            --query primaryConnectionString \
            --output tsv)

          # Create a new secret named 'svcbus-connstring' in backend processer container app
          az containerapp secret set \
            --name $BACKEND_SERVICE_NAME \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --secrets "svcbus-connstring=$SERVICE_BUS_CONNECTION_STRING"
