#
# Build stage
#
FROM maven:3.9.8-eclipse-temurin-21-alpine AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

#
# Run stage
#
FROM openjdk:21
COPY --from=build /home/app/target/InventoryApi-0.0.1-SNAPSHOT.jar /usr/local/lib/InventoryApi-0.0.1-SNAPSHOT.jar
EXPOSE 8080
USER 10014
ENTRYPOINT ["java","-jar","/usr/local/lib/InventoryApi-0.0.1-SNAPSHOT.jar"]